spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

app:
  jwt:
    secret: ${APP_JWT_SECRET:CHANGE_ME_JWT_SECRET}
    expire-ms: 86400000
  kafka:
    enabled: false
  minio:
    enabled: false
