# ??? Nacos ????
# Data ID: seataServer.properties
# Group:   SEATA_GROUP

# ??? -> TC ????????? seata.tx-service-group ???
service.vgroupMapping.my_test_tx_group=default

# Seata Server ????
store.mode=db
store.session.mode=db
store.lock.mode=db
store.db.datasource=druid
store.db.dbType=mysql
store.db.driverClassName=com.mysql.cj.jdbc.Driver
store.db.url=jdbc:mysql://127.0.0.1:3306/seata?rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
store.db.user=root
store.db.password=CHANGE_ME_SEATA_DB_PASSWORD
store.db.minConn=5
store.db.maxConn=100
store.db.globalTable=global_table
store.db.branchTable=branch_table
store.db.lockTable=lock_table
store.db.distributedLockTable=distributed_lock
store.db.queryLimit=100
store.db.maxWait=5000
